name: Keep Bharati Sweets Awake

on:
  schedule:
    - cron: '*/12 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Status Endpoint
        run: |
          curl -f https://bharati-sweets-prod.onrender.com/status || exit 1
          echo "Ping successful"

      - name: Ping API Status Endpoint
        run: |
          curl -f https://bharati-sweets-prod.onrender.com/api/status || exit 1
          echo "API Ping successful"
